use super::MessageKey;

pub const fn text(key: MessageKey) -> &'static str {
    match key {
        MessageKey::AppTitle => "HookStat 可靠性中心",
        MessageKey::NavOverview => "概览",
        MessageKey::NavHooks => "钩子",
        MessageKey::NavChanges => "变更",
        MessageKey::NavDiagnostics => "诊断",
        MessageKey::NavSettings => "设置",
        MessageKey::ViewOverview => "可靠性概览",
        MessageKey::ViewHooks => "钩子目录",
        MessageKey::ViewChanges => "变更与历史",
        MessageKey::ViewChangeDetail => "变更证据",
        MessageKey::ViewHookDetail => "钩子详情",
        MessageKey::ViewFailureClusters => "失败聚类",
        MessageKey::ViewFailureClusterDetail => "失败聚类详情",
        MessageKey::ViewDiagnostics => "只读诊断",
        MessageKey::ViewSettings => "界面设置",
        MessageKey::SectionNavigation => "分区",
        MessageKey::SectionRuntimeSummary => "运行时摘要",
        MessageKey::SectionRiskyHooks => "高风险钩子",
        MessageKey::SectionChanges => "最近变更",
        MessageKey::SectionRecentFailures => "最近失败",
        MessageKey::SectionTerminalBreakdown => "终止状态明细",
        MessageKey::SectionTimeline => "时间线",
        MessageKey::SectionIntelligence => "可靠性智能",
        MessageKey::SectionTrends => "趋势",
        MessageKey::SectionRevisionComparison => "修订版本比较",
        MessageKey::SectionFailureFingerprints => "失败指纹",
        MessageKey::SectionAlias => "人类别名",
        MessageKey::SectionDiagnostics => "运行检查",
        MessageKey::SectionInterface => "人机界面",
        MessageKey::SectionTechnicalMetadata => "高级技术元数据",
        MessageKey::SectionRuntimeConfiguration => "运行时配置",
        MessageKey::SectionReliabilitySummary => "可靠性摘要",
        MessageKey::SectionObservationHistory => "观测历史",
        MessageKey::SectionRuntimeIssues => "运行时问题",
        MessageKey::FieldRuntime => "运行时",
        MessageKey::FieldCoverage => "覆盖范围",
        MessageKey::FieldTotalRuns => "总运行次数",
        MessageKey::FieldRunCount => "运行次数",
        MessageKey::FieldFailureRate => "失败率",
        MessageKey::FieldHealth => "健康状态",
        MessageKey::FieldHealthExplanation => "健康说明",
        MessageKey::FieldEvent => "事件",
        MessageKey::FieldInternalIdentity => "内部标识",
        MessageKey::FieldRevision => "修订版本",
        MessageKey::FieldCurrentRevision => "当前修订版本",
        MessageKey::FieldPreviousRevision => "上一修订版本",
        MessageKey::FieldSuccesses => "成功",
        MessageKey::FieldFailures => "失败",
        MessageKey::FieldSamples => "终止样本",
        MessageKey::FieldWindow => "时间范围",
        MessageKey::FieldSearch => "搜索",
        MessageKey::FieldFilter => "筛选",
        MessageKey::FieldSort => "排序",
        MessageKey::FieldIncompleteReceipts => "不完整回执",
        MessageKey::FieldMalformedReceipts => "格式错误回执",
        MessageKey::FieldLanguage => "语言",
        MessageKey::FieldSavedLanguage => "已保存语言",
        MessageKey::FieldColor => "颜色",
        MessageKey::FieldSavedColor => "已保存颜色",
        MessageKey::FieldRisk => "风险",
        MessageKey::FieldRiskScore => "风险评分",
        MessageKey::FieldConfidence => "样本置信度",
        MessageKey::FieldClassification => "分类",
        MessageKey::FieldPreviousPeriod => "上一周期",
        MessageKey::FieldRecency => "近期性",
        MessageKey::FieldImpact => "影响",
        MessageKey::FieldFirstSeen => "首次发现",
        MessageKey::FieldLastSeen => "最后发现",
        MessageKey::FieldLatestEvidence => "最新证据",
        MessageKey::FieldAlias => "别名",
        MessageKey::FieldAffectedHooks => "受影响钩子",
        MessageKey::FieldOccurrences => "发生次数",
        MessageKey::FieldDataFreshness => "数据新鲜度",
        MessageKey::FieldRevisionCount => "历史修订数",
        MessageKey::FieldObservationStatus => "观测状态",
        MessageKey::FieldMetricScope => "指标范围",
        MessageKey::FieldChangeOccurred => "变更发生时间",
        MessageKey::FieldReason => "原因",
        MessageKey::FieldFullRevision => "完整修订版本",
        MessageKey::FieldInstalled => "已安装",
        MessageKey::FieldActive => "活动",
        MessageKey::FieldReview => "审查",
        MessageKey::FieldDescription => "描述",
        MessageKey::FieldEnabled => "已启用",
        MessageKey::FieldDisabled => "已禁用",
        MessageKey::FieldManaged => "受管理",
        MessageKey::FieldMatcher => "匹配器",
        MessageKey::FieldSource => "来源",
        MessageKey::FieldHandlerType => "处理程序类型",
        MessageKey::FieldCommand => "命令",
        MessageKey::FieldMcpServer => "MCP 服务器",
        MessageKey::FieldMcpTool => "MCP 工具",
        MessageKey::FieldPrompt => "提示",
        MessageKey::FieldAgent => "代理",
        MessageKey::FieldMode => "模式",
        MessageKey::FieldTimeout => "超时",
        MessageKey::FieldAdditionalContext => "附加上下文",
        MessageKey::FieldTrust => "信任",
        MessageKey::FieldNeedsReview => "需要审查",
        MessageKey::ValueSync => "同步",
        MessageKey::ValueAsync => "异步",
        MessageKey::ValueTrusted => "已信任",
        MessageKey::ValueUntrusted => "未信任",
        MessageKey::ValueModified => "已修改",
        MessageKey::RuntimeIssueWarning => "警告",
        MessageKey::RuntimeIssueError => "错误",
        MessageKey::HintFocusEvents => "Enter 聚焦事件",
        MessageKey::HintOpenHandlers => "Enter 打开处理程序",
        MessageKey::ColumnName => "名称",
        MessageKey::ColumnEvent => "事件",
        MessageKey::ColumnRuntime => "运行时",
        MessageKey::ColumnFailureRate => "失败率",
        MessageKey::ColumnTrend => "趋势",
        MessageKey::ColumnRisk => "风险",
        MessageKey::ColumnInstalled => "已安装",
        MessageKey::ColumnActive => "活动",
        MessageKey::ColumnReview => "审查",
        MessageKey::ColumnHealth => "健康",
        MessageKey::ColumnDescription => "描述",
        MessageKey::StateLoading => "正在加载已接纳的可靠性数据…",
        MessageKey::StateEmpty => "尚无已接纳的回执记录；这并不表示 0.00% 健康。",
        MessageKey::StateEmptySearch => "没有钩子匹配当前搜索或筛选条件。",
        MessageKey::StateRefreshFailed => "刷新失败；已接纳的历史记录仍被保留。",
        MessageKey::StateRuntimeCatalogLoading => "正在加载当前运行时目录…",
        MessageKey::StateRuntimeCatalogStale => "运行时刷新失败；正在显示上次已接纳的目录。",
        MessageKey::StateRuntimeCatalogUnavailable => "当前运行时目录不可用；可靠性历史保持独立。",
        MessageKey::StateReliabilityUnavailable => "可靠性不可用",
        MessageKey::StateNotObserved => "未观测",
        MessageKey::StateJoinAmbiguous => "历史关联不明确",
        MessageKey::StateTimelineUnavailable => "可靠性智能功能尚未接纳，时间线暂不可用。",
        MessageKey::StateInsufficientHistory => "历史不足",
        MessageKey::StateInsufficientSamples => "样本不足",
        MessageKey::StateCoverageLimited => "覆盖范围受限",
        MessageKey::StateNoRecentFailures => "此时间范围内没有最近的执行失败。",
        MessageKey::StateHistoricalOnly => "仅在此周期外有历史记录；这不表示钩子已停用或移除。",
        MessageKey::StatePreferenceClean => "没有待应用的语言变更。",
        MessageKey::StatePreferenceDirty => "语言变更已暂存；应用后才会保存。",
        MessageKey::StatePreferenceSaved => "语言偏好已保存到本地。",
        MessageKey::StatePreferenceConflict => "语言偏好已被其他位置修改；应用被拒绝。",
        MessageKey::StatePreferenceSaveFailed => "无法安全保存语言偏好。",
        MessageKey::StateAliasClean => "没有待应用的别名变更。",
        MessageKey::StateAliasDirty => "别名变更已暂存；应用后才会保存。",
        MessageKey::StateAliasSaved => "别名已保存到 HookStat 展示元数据。",
        MessageKey::StateAliasConflict => "别名已在其他位置变更；应用被拒绝。",
        MessageKey::StateAliasSaveFailed => "无法安全保存别名。",
        MessageKey::StateObservedInSelectedPeriod => "在选定周期内已观测",
        MessageKey::StatusHealthy => "✓ 健康",
        MessageKey::StatusDegraded => "! 已降级",
        MessageKey::StatusCoverageLimited => "! 覆盖受限",
        MessageKey::StatusNoTerminalSamples => "! 没有终止样本",
        MessageKey::StatusUnavailable => "不可用",
        MessageKey::StatusRegression => "↑ 回归",
        MessageKey::StatusImprovement => "↓ 改善",
        MessageKey::StatusStable => "→ 稳定",
        MessageKey::StatusInsufficientEvidence => "证据不足",
        MessageKey::ChangeRegression => "回归",
        MessageKey::ChangeRecovery => "恢复",
        MessageKey::ChangeRevision => "修订版本变更",
        MessageKey::ChangeNewHook => "新接纳钩子",
        MessageKey::DiagnosticPass => "通过",
        MessageKey::DiagnosticWarning => "需注意",
        MessageKey::DiagnosticFail => "失败",
        MessageKey::DiagnosticUnknown => "未知",
        MessageKey::DiagnosticUnsupported => "不支持",
        MessageKey::DiagnosticHookStatBinary => "HookStat 二进制",
        MessageKey::DiagnosticCodexBinary => "Codex 二进制",
        MessageKey::DiagnosticEffectiveRuntime => "有效运行时",
        MessageKey::DiagnosticInstrumentation => "插桩",
        MessageKey::DiagnosticTrust => "信任",
        MessageKey::DiagnosticReceiptSpool => "回执缓冲区",
        MessageKey::DiagnosticLedger => "SQLite 台账",
        MessageKey::DiagnosticReceiptIntegrity => "回执完整性",
        MessageKey::DiagnosticEvidenceCoverage => "证据覆盖范围",
        MessageKey::DiagnosticPathIdentity => "Windows PATH 标识",
        MessageKey::DiagnosticEvidenceFreshness => "最新证据",
        MessageKey::DiagnosticHookStatBinaryExplanation => "只确认正在运行的 HookStat 构建版本。",
        MessageKey::DiagnosticCodexBinaryExplanation => "执行受限的 Codex 版本检查，不会更改配置。",
        MessageKey::DiagnosticEffectiveRuntimeExplanation => {
            "可用时使用 Codex 的只读有效钩子视图。"
        }
        MessageKey::DiagnosticInstrumentationExplanation => {
            "仅读取受支持配置，绝不会应用或修复钩子。"
        }
        MessageKey::DiagnosticTrustExplanation => "报告只读有效信任状态，绝不写入信任。",
        MessageKey::DiagnosticReceiptSpoolExplanation => {
            "检查已有缓冲区，不会创建、修复或写入回执。"
        }
        MessageKey::DiagnosticLedgerExplanation => {
            "以只读方式打开已有台账；缺失状态绝不会被当作健康。"
        }
        MessageKey::DiagnosticReceiptIntegrityExplanation => {
            "格式错误和不完整回执的计数始终明确显示。"
        }
        MessageKey::DiagnosticEvidenceCoverageExplanation => {
            "受支持和不受支持的覆盖范围均保持可见；未知绝不等同健康。"
        }
        MessageKey::DiagnosticPathIdentityExplanation => {
            "仅与 Windows 代理执行相关；其他平台显示为不支持。"
        }
        MessageKey::DiagnosticEvidenceFreshnessExplanation => {
            "仅在存在时测量最新的已净化证据时间戳。"
        }
        MessageKey::DiagnosticHandlerCounts => {
            "已发现 {discovered} / 已插桩 {instrumented} / 不支持 {unsupported}"
        }
        MessageKey::DiagnosticEvidenceAgeMinutes => "{minutes} 分钟前",
        MessageKey::LanguageAuto => "自动",
        MessageKey::LanguageEnUs => "英语 (en-US)",
        MessageKey::LanguageZhCn => "简体中文 (zh-CN)",
        MessageKey::ColorAuto => "自动",
        MessageKey::ColorAlways => "始终使用",
        MessageKey::ColorNever => "从不使用",
        MessageKey::CoverageComplete => "完整",
        MessageKey::CoveragePartial => "部分",
        MessageKey::CoverageSyncOnly => "仅同步",
        MessageKey::CoverageBestEffort => "尽力而为",
        MessageKey::CoverageUnknown => "未知",
        MessageKey::CoverageNotAdmitted => "未接纳",
        MessageKey::CoverageSyntheticFixture => "合成样例",
        MessageKey::WindowToday => "今天",
        MessageKey::WindowLast24Hours => "最近 24 小时",
        MessageKey::WindowLast7Days => "最近 7 天",
        MessageKey::WindowLast30Days => "最近 30 天",
        MessageKey::WindowAll => "全部时间",
        MessageKey::PeriodAll => "全部",
        MessageKey::RuntimeCodex => "Codex",
        MessageKey::RuntimeDeepSeekHarness => "DeepSeek Harness",
        MessageKey::RuntimeOpenCode => "OpenCode",
        MessageKey::EventSessionStart => "会话开始",
        MessageKey::EventSessionEnd => "会话结束",
        MessageKey::EventUserPromptSubmit => "提交提示",
        MessageKey::EventPreToolUse => "工具调用前",
        MessageKey::EventPostToolUse => "工具调用后",
        MessageKey::EventPermissionRequest => "权限请求",
        MessageKey::EventPreCompact => "压缩前",
        MessageKey::EventPostCompact => "压缩后",
        MessageKey::EventStop => "停止",
        MessageKey::EventSubagentStart => "子代理开始",
        MessageKey::EventSubagentStop => "子代理停止",
        MessageKey::TerminalCompleted => "已完成",
        MessageKey::TerminalFailed => "失败",
        MessageKey::TerminalBlocked => "已阻止",
        MessageKey::TerminalStopped => "已停止",
        MessageKey::TerminalTimedOut => "超时",
        MessageKey::TerminalProtocolFailure => "协议失败",
        MessageKey::TerminalIncomplete => "不完整",
        MessageKey::TerminalUnknown => "未知",
        MessageKey::SortFailureRate => "失败率",
        MessageKey::SortName => "名称",
        MessageKey::SortRuns => "运行次数",
        MessageKey::SortRisk => "风险评分",
        MessageKey::FilterFailuresOnly => "仅失败钩子",
        MessageKey::FilterAllHooks => "全部钩子",
        MessageKey::IdentityHook => "钩子",
        MessageKey::RateWithSample => "{rate}%（{samples}）",
        MessageKey::SampleCount => "样本={count}",
        MessageKey::FingerprintExitNonzero => "非零退出",
        MessageKey::FingerprintTimedOut => "超时",
        MessageKey::FingerprintProtocolFailure => "协议失败",
        MessageKey::FingerprintExecutionFailed => "执行失败",
        MessageKey::FooterNavigate => "导航",
        MessageKey::FooterPage => "翻页",
        MessageKey::FooterOpen => "打开",
        MessageKey::FooterHelp => "帮助",
        MessageKey::FooterSelect => "选择",
        MessageKey::FooterEdit => "编辑",
        MessageKey::FooterBack => "返回",
        MessageKey::FooterRefresh => "刷新",
        MessageKey::FooterQuit => "退出",
        MessageKey::FooterFocusContent => "内容",
        MessageKey::FooterFocusNavigation => "导航栏",
        MessageKey::FooterSearch => "搜索",
        MessageKey::FooterFilter => "筛选",
        MessageKey::FooterSort => "排序",
        MessageKey::FooterChange => "更改",
        MessageKey::FooterApply => "应用",
        MessageKey::FooterRevert => "还原",
        MessageKey::FooterCancel => "取消",
        MessageKey::FooterDiscard => "放弃",
        MessageKey::FooterDismiss => "关闭",
        MessageKey::HelpTitle => "帮助",
        MessageKey::HelpNavigation => "↑↓ 或 j/k 直接切换页面；Enter 进入当前本地交互。",
        MessageKey::HelpPeriods => {
            "周期：t 今天，1 过去 24 小时，7 过去 7 天，3 过去 30 天，a 全部。"
        }
        MessageKey::HelpHooks => {
            "钩子：Enter 聚焦事件，然后打开处理程序和详情；Esc 返回上一层；r 刷新运行时目录和可靠性。"
        }
        MessageKey::HelpChanges => {
            "变更：Enter 选择事件后打开证据和有序修订时间线。历史记录绝不证明钩子已被移除。"
        }
        MessageKey::HelpDetail => {
            "钩子详情：f 打开安全失败聚类；↑↓ 滚动，PgUp/PgDn 翻页，Esc 返回目录。"
        }
        MessageKey::HelpSettings => {
            "设置：Enter 编辑/完成，↑↓ 选择字段，←→ 调整草稿，a 应用，r 还原；草稿有更改时 q 会确认。"
        }
        MessageKey::HelpRefresh => "r 分别刷新当前钩子目录和可靠性。所有失败率都带样本数。",
        MessageKey::MinimumTerminal => "请调整到至少 24x10",
        MessageKey::FailureRateUnavailableZeroSamples => "不可用（终态样本 0；无终态样本）",
        MessageKey::ScopeSelectedAllRevisions => "已选 {period}，全部修订版本",
        MessageKey::ScopePeriodAllRevisions => "{period}，全部修订版本",
        MessageKey::ScopeAllObservedAllRevisions => "全部观测时间，全部修订版本",
        MessageKey::ScopeAllObservedCurrentRevision => "全部观测时间，当前修订版本",
        MessageKey::ScopeAllObservedPreviousRevision => "全部观测时间，上一修订版本",
        MessageKey::ScopeAllObservedRevisionTimeline => "全部观测时间，修订版本时间线",
        MessageKey::ScopeTerminalSamples => "已选范围内 {samples}",
        MessageKey::CoverageExplanationComplete => "此范围内终态证据完整。",
        MessageKey::CoverageExplanationPartial => "已观察到部分证据；终态覆盖不完整。",
        MessageKey::CoverageExplanationSyncOnly => "仅覆盖同步观察。",
        MessageKey::CoverageExplanationBestEffort => "证据为尽力而为，可能不完整。",
        MessageKey::CoverageExplanationUnknown => "覆盖范围未知；可靠性不是健康结论。",
        MessageKey::CoverageExplanationNotAdmitted => "没有已接纳的证据来源覆盖此 Hook。",
        MessageKey::CoverageExplanationSyntheticFixture => "合成样例覆盖；不是实时运行时证据。",
        MessageKey::RiskLow => "低风险",
        MessageKey::RiskGuarded => "需关注风险",
        MessageKey::RiskElevated => "较高风险",
        MessageKey::RiskHigh => "高风险",
        MessageKey::RiskReasonFailures => "已选范围内观察到执行失败。",
        MessageKey::RiskReasonNoTerminalSamples => "无终态样本；这不是健康结果。",
        MessageKey::RiskReasonComplete => "已选范围内未观察到失败。",
        MessageKey::RiskReasonIncomplete => "未观察到失败；终态覆盖不完整。",
        MessageKey::TimeUnavailable => "时间不可用",
        MessageKey::TimeJustNow => "刚刚",
        MessageKey::TimeMinuteAgo => "1 分钟前",
        MessageKey::TimeMinutesAgo => "{count} 分钟前",
        MessageKey::TimeHourAgo => "1 小时前",
        MessageKey::TimeHoursAgo => "{count} 小时前",
        MessageKey::TimeDayAgo => "1 天前",
        MessageKey::TimeDaysAgo => "{count} 天前",
    }
}
