use super::MessageKey;

pub const fn text(key: MessageKey) -> &'static str {
    match key {
        MessageKey::AppTitle => "HookStat 可靠性中心",
        MessageKey::NavOverview => "概览",
        MessageKey::NavHooks => "钩子",
        MessageKey::NavDiagnostics => "诊断",
        MessageKey::ViewOverview => "可靠性概览",
        MessageKey::ViewHooks => "钩子可靠性",
        MessageKey::ViewHookDetail => "钩子详情",
        MessageKey::ViewDiagnostics => "只读诊断",
        MessageKey::SectionNavigation => "导航",
        MessageKey::SectionRuntimeSummary => "运行时摘要",
        MessageKey::SectionRiskyHooks => "高风险钩子",
        MessageKey::SectionRecentFailures => "最近失败",
        MessageKey::SectionTerminalBreakdown => "终止状态明细",
        MessageKey::SectionTimeline => "时间线",
        MessageKey::SectionDiagnostics => "运行检查",
        MessageKey::FieldRuntime => "运行时",
        MessageKey::FieldCoverage => "覆盖范围",
        MessageKey::FieldTotalRuns => "总运行次数",
        MessageKey::FieldRunCount => "运行次数",
        MessageKey::FieldFailureRate => "失败率",
        MessageKey::FieldHealth => "健康状态",
        MessageKey::FieldEvent => "事件",
        MessageKey::FieldInternalIdentity => "内部标识",
        MessageKey::FieldRevision => "修订版本",
        MessageKey::FieldSuccesses => "成功",
        MessageKey::FieldFailures => "失败",
        MessageKey::FieldSamples => "终止样本",
        MessageKey::FieldWindow => "时间范围",
        MessageKey::FieldSearch => "搜索",
        MessageKey::FieldFilter => "筛选",
        MessageKey::FieldSort => "排序",
        MessageKey::FieldIncompleteReceipts => "不完整回执",
        MessageKey::FieldMalformedReceipts => "格式错误回执",
        MessageKey::ColumnName => "名称",
        MessageKey::ColumnEvent => "事件",
        MessageKey::ColumnRuntime => "运行时",
        MessageKey::ColumnFailureRate => "失败率",
        MessageKey::ColumnTrend => "趋势",
        MessageKey::StateLoading => "正在加载已接纳的可靠性数据…",
        MessageKey::StateEmpty => "尚无已接纳的回执记录；这并不表示 0.00% 健康。",
        MessageKey::StateEmptySearch => "没有钩子匹配当前搜索或筛选条件。",
        MessageKey::StateRefreshFailed => "刷新失败；已接纳的历史记录仍被保留。",
        MessageKey::StateTimelineUnavailable => "可靠性智能功能尚未接纳，时间线暂不可用。",
        MessageKey::StateNoRecentFailures => "此时间范围内没有最近的执行失败。",
        MessageKey::StatusHealthy => "✓ 健康",
        MessageKey::StatusDegraded => "! 已降级",
        MessageKey::StatusCoverageLimited => "! 覆盖受限",
        MessageKey::StatusNoTerminalSamples => "! 没有终止样本",
        MessageKey::StatusUnavailable => "不可用",
        MessageKey::DiagnosticHealthy => "通过",
        MessageKey::DiagnosticWarning => "需注意",
        MessageKey::DiagnosticUnavailable => "未检查",
        MessageKey::DiagnosticRuntimeSnapshot => "运行时快照",
        MessageKey::DiagnosticEvidenceCoverage => "证据覆盖范围",
        MessageKey::DiagnosticReceiptIntegrity => "回执完整性",
        MessageKey::DiagnosticInstrumentation => "插桩",
        MessageKey::DiagnosticTrust => "信任",
        MessageKey::DiagnosticReceiptStorage => "回执存储",
        MessageKey::DiagnosticRuntimeSnapshotExplanation => {
            "来自已接纳的可靠性快照；不会运行运行时探测。"
        }
        MessageKey::DiagnosticEvidenceCoverageExplanation => {
            "按已接纳状态报告覆盖范围，绝不会默认为健康的零失败。"
        }
        MessageKey::DiagnosticReceiptIntegrityExplanation => {
            "计数来自已接纳的快照；格式错误或不完整回执始终可见。"
        }
        MessageKey::DiagnosticInstrumentationExplanation => {
            "G01 未检查；此视图不会读取或更改 Codex 配置。"
        }
        MessageKey::DiagnosticTrustExplanation => "G01 未检查；此视图不会查询或更改 Codex 信任。",
        MessageKey::DiagnosticReceiptStorageExplanation => {
            "存储探测延后至 G04；此视图不会检查文件系统。"
        }
        MessageKey::CoverageComplete => "完整",
        MessageKey::CoveragePartial => "部分",
        MessageKey::CoverageSyncOnly => "仅同步",
        MessageKey::CoverageBestEffort => "尽力而为",
        MessageKey::CoverageUnknown => "未知",
        MessageKey::CoverageNotAdmitted => "未接纳",
        MessageKey::CoverageSyntheticFixture => "合成样例",
        MessageKey::WindowLast24Hours => "最近 24 小时",
        MessageKey::WindowLast7Days => "最近 7 天",
        MessageKey::WindowLast30Days => "最近 30 天",
        MessageKey::WindowAll => "全部时间",
        MessageKey::RuntimeCodex => "Codex",
        MessageKey::RuntimeDeepSeekHarness => "DeepSeek Harness",
        MessageKey::RuntimeOpenCode => "OpenCode",
        MessageKey::EventSessionStart => "会话开始",
        MessageKey::EventSessionEnd => "会话结束",
        MessageKey::EventUserPromptSubmit => "提交提示",
        MessageKey::EventPreToolUse => "工具调用前",
        MessageKey::EventPostToolUse => "工具调用后",
        MessageKey::EventPermissionRequest => "权限请求",
        MessageKey::EventPreCompact => "压缩前",
        MessageKey::EventPostCompact => "压缩后",
        MessageKey::EventStop => "停止",
        MessageKey::EventSubagentStart => "子代理开始",
        MessageKey::EventSubagentStop => "子代理停止",
        MessageKey::TerminalCompleted => "已完成",
        MessageKey::TerminalFailed => "失败",
        MessageKey::TerminalBlocked => "已阻止",
        MessageKey::TerminalStopped => "已停止",
        MessageKey::TerminalTimedOut => "超时",
        MessageKey::TerminalProtocolFailure => "协议失败",
        MessageKey::TerminalIncomplete => "不完整",
        MessageKey::TerminalUnknown => "未知",
        MessageKey::SortFailureRate => "失败率",
        MessageKey::SortName => "名称",
        MessageKey::SortRuns => "运行次数",
        MessageKey::FilterFailuresOnly => "仅失败钩子",
        MessageKey::FilterAllHooks => "全部钩子",
        MessageKey::IdentityHook => "钩子",
        MessageKey::RateWithSample => "{rate}%（{samples}）",
        MessageKey::SampleCount => "样本={count}",
        MessageKey::FooterNavigate => "导航",
        MessageKey::FooterOpen => "打开",
        MessageKey::FooterBack => "返回",
        MessageKey::FooterRefresh => "刷新",
        MessageKey::FooterQuit => "退出",
        MessageKey::FooterFocusContent => "内容",
        MessageKey::FooterFocusNavigation => "导航栏",
        MessageKey::FooterSearch => "搜索",
        MessageKey::FooterFilter => "筛选",
        MessageKey::FooterSort => "排序",
        MessageKey::MinimumTerminal => "请调整到至少 24x10",
    }
}
