use super::MessageKey;

pub const fn text(key: MessageKey) -> &'static str {
    match key {
        MessageKey::AppTitle => "HookStat 可靠性中心",
        MessageKey::NavOverview => "概览",
        MessageKey::NavHooks => "钩子",
        MessageKey::NavDiagnostics => "诊断",
        MessageKey::NavSettings => "设置",
        MessageKey::ViewOverview => "可靠性概览",
        MessageKey::ViewHooks => "钩子可靠性",
        MessageKey::ViewHookDetail => "钩子详情",
        MessageKey::ViewDiagnostics => "只读诊断",
        MessageKey::ViewSettings => "界面设置",
        MessageKey::SectionNavigation => "导航",
        MessageKey::SectionRuntimeSummary => "运行时摘要",
        MessageKey::SectionRiskyHooks => "高风险钩子",
        MessageKey::SectionRecentFailures => "最近失败",
        MessageKey::SectionTerminalBreakdown => "终止状态明细",
        MessageKey::SectionTimeline => "时间线",
        MessageKey::SectionIntelligence => "可靠性智能",
        MessageKey::SectionTrends => "趋势",
        MessageKey::SectionRevisionComparison => "修订版本比较",
        MessageKey::SectionFailureFingerprints => "失败指纹",
        MessageKey::SectionDiagnostics => "运行检查",
        MessageKey::SectionInterface => "人机界面",
        MessageKey::FieldRuntime => "运行时",
        MessageKey::FieldCoverage => "覆盖范围",
        MessageKey::FieldTotalRuns => "总运行次数",
        MessageKey::FieldRunCount => "运行次数",
        MessageKey::FieldFailureRate => "失败率",
        MessageKey::FieldHealth => "健康状态",
        MessageKey::FieldEvent => "事件",
        MessageKey::FieldInternalIdentity => "内部标识",
        MessageKey::FieldRevision => "修订版本",
        MessageKey::FieldSuccesses => "成功",
        MessageKey::FieldFailures => "失败",
        MessageKey::FieldSamples => "终止样本",
        MessageKey::FieldWindow => "时间范围",
        MessageKey::FieldSearch => "搜索",
        MessageKey::FieldFilter => "筛选",
        MessageKey::FieldSort => "排序",
        MessageKey::FieldIncompleteReceipts => "不完整回执",
        MessageKey::FieldMalformedReceipts => "格式错误回执",
        MessageKey::FieldLanguage => "语言",
        MessageKey::FieldSavedLanguage => "已保存语言",
        MessageKey::FieldColor => "颜色",
        MessageKey::FieldSavedColor => "已保存颜色",
        MessageKey::FieldRisk => "风险",
        MessageKey::FieldRiskScore => "风险评分",
        MessageKey::FieldConfidence => "样本置信度",
        MessageKey::FieldClassification => "分类",
        MessageKey::FieldPreviousPeriod => "上一周期",
        MessageKey::FieldRecency => "近期性",
        MessageKey::FieldImpact => "影响",
        MessageKey::ColumnName => "名称",
        MessageKey::ColumnEvent => "事件",
        MessageKey::ColumnRuntime => "运行时",
        MessageKey::ColumnFailureRate => "失败率",
        MessageKey::ColumnTrend => "趋势",
        MessageKey::ColumnRisk => "风险",
        MessageKey::StateLoading => "正在加载已接纳的可靠性数据…",
        MessageKey::StateEmpty => "尚无已接纳的回执记录；这并不表示 0.00% 健康。",
        MessageKey::StateEmptySearch => "没有钩子匹配当前搜索或筛选条件。",
        MessageKey::StateRefreshFailed => "刷新失败；已接纳的历史记录仍被保留。",
        MessageKey::StateTimelineUnavailable => "可靠性智能功能尚未接纳，时间线暂不可用。",
        MessageKey::StateInsufficientHistory => "历史不足",
        MessageKey::StateInsufficientSamples => "样本不足",
        MessageKey::StateCoverageLimited => "覆盖范围受限",
        MessageKey::StateNoRecentFailures => "此时间范围内没有最近的执行失败。",
        MessageKey::StatePreferenceClean => "没有待应用的语言变更。",
        MessageKey::StatePreferenceDirty => "语言变更已暂存；应用后才会保存。",
        MessageKey::StatePreferenceSaved => "语言偏好已保存到本地。",
        MessageKey::StatePreferenceConflict => "语言偏好已被其他位置修改；应用被拒绝。",
        MessageKey::StatePreferenceSaveFailed => "无法安全保存语言偏好。",
        MessageKey::StatusHealthy => "✓ 健康",
        MessageKey::StatusDegraded => "! 已降级",
        MessageKey::StatusCoverageLimited => "! 覆盖受限",
        MessageKey::StatusNoTerminalSamples => "! 没有终止样本",
        MessageKey::StatusUnavailable => "不可用",
        MessageKey::StatusRegression => "↑ 回归",
        MessageKey::StatusImprovement => "↓ 改善",
        MessageKey::StatusStable => "→ 稳定",
        MessageKey::StatusInsufficientEvidence => "证据不足",
        MessageKey::DiagnosticPass => "通过",
        MessageKey::DiagnosticWarning => "需注意",
        MessageKey::DiagnosticFail => "失败",
        MessageKey::DiagnosticUnknown => "未知",
        MessageKey::DiagnosticUnsupported => "不支持",
        MessageKey::DiagnosticHookStatBinary => "HookStat 二进制",
        MessageKey::DiagnosticCodexBinary => "Codex 二进制",
        MessageKey::DiagnosticEffectiveRuntime => "有效运行时",
        MessageKey::DiagnosticInstrumentation => "插桩",
        MessageKey::DiagnosticTrust => "信任",
        MessageKey::DiagnosticReceiptSpool => "回执缓冲区",
        MessageKey::DiagnosticLedger => "SQLite 台账",
        MessageKey::DiagnosticReceiptIntegrity => "回执完整性",
        MessageKey::DiagnosticEvidenceCoverage => "证据覆盖范围",
        MessageKey::DiagnosticPathIdentity => "Windows PATH 标识",
        MessageKey::DiagnosticEvidenceFreshness => "最新证据",
        MessageKey::DiagnosticHookStatBinaryExplanation => "只确认正在运行的 HookStat 构建版本。",
        MessageKey::DiagnosticCodexBinaryExplanation => "执行受限的 Codex 版本检查，不会更改配置。",
        MessageKey::DiagnosticEffectiveRuntimeExplanation => {
            "可用时使用 Codex 的只读有效钩子视图。"
        }
        MessageKey::DiagnosticInstrumentationExplanation => {
            "仅读取受支持配置，绝不会应用或修复钩子。"
        }
        MessageKey::DiagnosticTrustExplanation => "报告只读有效信任状态，绝不写入信任。",
        MessageKey::DiagnosticReceiptSpoolExplanation => {
            "检查已有缓冲区，不会创建、修复或写入回执。"
        }
        MessageKey::DiagnosticLedgerExplanation => {
            "以只读方式打开已有台账；缺失状态绝不会被当作健康。"
        }
        MessageKey::DiagnosticReceiptIntegrityExplanation => {
            "格式错误和不完整回执的计数始终明确显示。"
        }
        MessageKey::DiagnosticEvidenceCoverageExplanation => {
            "受支持和不受支持的覆盖范围均保持可见；未知绝不等同健康。"
        }
        MessageKey::DiagnosticPathIdentityExplanation => {
            "仅与 Windows 代理执行相关；其他平台显示为不支持。"
        }
        MessageKey::DiagnosticEvidenceFreshnessExplanation => {
            "仅在存在时测量最新的已净化证据时间戳。"
        }
        MessageKey::DiagnosticHandlerCounts => {
            "已发现 {discovered} / 已插桩 {instrumented} / 不支持 {unsupported}"
        }
        MessageKey::DiagnosticEvidenceAgeMinutes => "{minutes} 分钟前",
        MessageKey::LanguageAuto => "自动",
        MessageKey::LanguageEnUs => "英语 (en-US)",
        MessageKey::LanguageZhCn => "简体中文 (zh-CN)",
        MessageKey::ColorAuto => "自动",
        MessageKey::ColorAlways => "始终使用",
        MessageKey::ColorNever => "从不使用",
        MessageKey::CoverageComplete => "完整",
        MessageKey::CoveragePartial => "部分",
        MessageKey::CoverageSyncOnly => "仅同步",
        MessageKey::CoverageBestEffort => "尽力而为",
        MessageKey::CoverageUnknown => "未知",
        MessageKey::CoverageNotAdmitted => "未接纳",
        MessageKey::CoverageSyntheticFixture => "合成样例",
        MessageKey::WindowLast24Hours => "最近 24 小时",
        MessageKey::WindowLast7Days => "最近 7 天",
        MessageKey::WindowLast30Days => "最近 30 天",
        MessageKey::WindowAll => "全部时间",
        MessageKey::RuntimeCodex => "Codex",
        MessageKey::RuntimeDeepSeekHarness => "DeepSeek Harness",
        MessageKey::RuntimeOpenCode => "OpenCode",
        MessageKey::EventSessionStart => "会话开始",
        MessageKey::EventSessionEnd => "会话结束",
        MessageKey::EventUserPromptSubmit => "提交提示",
        MessageKey::EventPreToolUse => "工具调用前",
        MessageKey::EventPostToolUse => "工具调用后",
        MessageKey::EventPermissionRequest => "权限请求",
        MessageKey::EventPreCompact => "压缩前",
        MessageKey::EventPostCompact => "压缩后",
        MessageKey::EventStop => "停止",
        MessageKey::EventSubagentStart => "子代理开始",
        MessageKey::EventSubagentStop => "子代理停止",
        MessageKey::TerminalCompleted => "已完成",
        MessageKey::TerminalFailed => "失败",
        MessageKey::TerminalBlocked => "已阻止",
        MessageKey::TerminalStopped => "已停止",
        MessageKey::TerminalTimedOut => "超时",
        MessageKey::TerminalProtocolFailure => "协议失败",
        MessageKey::TerminalIncomplete => "不完整",
        MessageKey::TerminalUnknown => "未知",
        MessageKey::SortFailureRate => "失败率",
        MessageKey::SortName => "名称",
        MessageKey::SortRuns => "运行次数",
        MessageKey::SortRisk => "风险评分",
        MessageKey::FilterFailuresOnly => "仅失败钩子",
        MessageKey::FilterAllHooks => "全部钩子",
        MessageKey::IdentityHook => "钩子",
        MessageKey::RateWithSample => "{rate}%（{samples}）",
        MessageKey::SampleCount => "样本={count}",
        MessageKey::FingerprintExitNonzero => "非零退出",
        MessageKey::FingerprintTimedOut => "超时",
        MessageKey::FingerprintProtocolFailure => "协议失败",
        MessageKey::FingerprintExecutionFailed => "执行失败",
        MessageKey::FooterNavigate => "导航",
        MessageKey::FooterPage => "翻页",
        MessageKey::FooterOpen => "打开",
        MessageKey::FooterBack => "返回",
        MessageKey::FooterRefresh => "刷新",
        MessageKey::FooterQuit => "退出",
        MessageKey::FooterFocusContent => "内容",
        MessageKey::FooterFocusNavigation => "导航栏",
        MessageKey::FooterSearch => "搜索",
        MessageKey::FooterFilter => "筛选",
        MessageKey::FooterSort => "排序",
        MessageKey::FooterChange => "更改",
        MessageKey::FooterApply => "应用",
        MessageKey::FooterRevert => "还原",
        MessageKey::MinimumTerminal => "请调整到至少 24x10",
    }
}
